
tasks:
  - name: Nuxt
    init: printf 'y\n' | yarn install
    command: yarn dev

ports:
  - port: 3000
    name: Nuxt
    visibility: public
  - port: 1337
    name: Vite HMR
    visibility: public

vscode:
  extensions:
    - johnsoncodehk.volar
    - johnsoncodehk.vscode-typescript-vue-plugin
